// Package custom hosts clonable one-off commands: stubs generated by
// `ginplate make:command Foo` land here (internal/commands/<snake>.go) and
// self-register via init(), so the CLI root picks them up with no manual
// edits. Registration is compile-time — rebuild after generating.
package custom

import (
	"sort"

	"github.com/spf13/cobra"
)

var (
	customRegistryNames []string
	customRegistry      = map[string]func() *cobra.Command{}
)

// RegisterCustom registers a constructor under use (e.g. "send-report").
// Later registrations with the same use replace earlier ones.
func RegisterCustom(use string, fn func() *cobra.Command) {
	if _, ok := customRegistry[use]; !ok {
		customRegistryNames = append(customRegistryNames, use)
	}
	customRegistry[use] = fn
}

// Registered returns registered constructors in sorted order,
// so `--help` output is stable.
func Registered() []*cobra.Command {
	names := append([]string(nil), customRegistryNames...)
	sort.Strings(names)
	out := make([]*cobra.Command, 0, len(names))
	for _, n := range names {
		if fn, ok := customRegistry[n]; ok && fn != nil {
			out = append(out, fn())
		}
	}
	return out
}
