package makecommand

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

// NewMakeCommandCmd builds the `make:command` generator: scaffolds a
// self-registering stub that appears as a top-level command after rebuild.
func NewMakeCommandCmd() *cobra.Command {
	var dir, pkgdir string
	var force, dryRun, syncOnly bool
	cmd := &cobra.Command{
		Use:   "make:command <Name>",
		Short: "Generate a new custom command file (auto-registered)",
		Long: `Generate a stub command in its own directory, e.g.:

	ginplate make:command SendReport   # writes internal/commands/send-report/send_report.go

The stub registers itself via init(), so after rebuilding it appears as
` + "`ginplate send-report`" + ` with no further edits.
Run with --sync (no Name) to only refresh the generated import list,
e.g. after deleting a command directory (delete generated.go first if
the tree no longer compiles).`,
		Args: cobra.RangeArgs(0, 1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if syncOnly {
				return syncCustomImports(cmd, pkgdir, dir, dryRun)
			}
			if len(args) != 1 {
				return fmt.Errorf("requires a NAME argument (or pass --sync)")
			}
			return generateCommand(cmd, pkgdir, dir, args[0], force, dryRun)
		},
	}
	cmd.Flags().StringVar(&dir, "dir", "internal/commands", "Parent directory for generated command folders (module-relative, run from repo root)")
	cmd.Flags().StringVar(&pkgdir, "pkgdir", "pkg/commands", "Directory holding generated.go (module-relative, run from repo root)")
	cmd.Flags().BoolVar(&syncOnly, "sync", false, "Only refresh pkg/commands/generated.go from disk, create nothing")
	cmd.Flags().BoolVar(&force, "force", false, "Overwrite the file if it already exists")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Print the file instead of writing it")
	return cmd
}

type commandNames struct {
	Use         string // e.g. send-report (CLI name + directory name)
	Dir         string // e.g. send-report (subdirectory under --dir)
	Pkg         string // e.g. sendreport (Go package name: letters+digits only)
	File        string // e.g. send_report.go
	Constructor string // e.g. newSendReportCmd
	Module      string // e.g. github.com/idehen-divine/GinPlate (from go.mod)
}

var validNameRe = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_-]*$`)

// deriveNames maps a name in any style (SendReport, send-report,
// send_report) to file, CLI, and constructor identifiers.
func deriveNames(raw string) (commandNames, error) {
	raw = strings.TrimSpace(raw)
	if !validNameRe.MatchString(raw) {
		return commandNames{}, fmt.Errorf("invalid name %q: use letters, digits, '-' or '_' (start with a letter)", raw)
	}
	var words []string
	for _, part := range strings.FieldsFunc(raw, func(r rune) bool { return r == '-' || r == '_' || r == ' ' }) {
		words = append(words, splitCamel(part)...)
	}
	lower := make([]string, len(words))
	for i, w := range words {
		lower[i] = strings.ToLower(w)
	}
	studly := ""
	for _, w := range words {
		studly += capitalize(w)
	}
	return commandNames{
		Use:         strings.Join(lower, "-"),
		Dir:         strings.Join(lower, "-"),
		Pkg:         strings.Join(lower, ""),
		File:        strings.Join(lower, "_") + ".go",
		Constructor: "new" + studly + "Cmd",
	}, nil
}

func splitCamel(s string) []string {
	var words []string
	start := 0
	for i := 1; i < len(s); i++ {
		c, p := s[i], s[i-1]
		if c >= 'A' && c <= 'Z' && ((p >= 'a' && p <= 'z') || (p >= '0' && p <= '9')) {
			words = append(words, s[start:i])
			start = i
		}
	}
	return append(words, s[start:])
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + strings.ToLower(s[1:])
}

var commandTemplate = template.Must(template.New("command").Parse(`package {{.Pkg}}

import (
	"fmt"

	"github.com/spf13/cobra"

	"{{.Module}}/internal/commands"
)

func init() {
	custom.RegisterCustom("{{.Use}}", {{.Constructor}})
}

// {{.Constructor}} was generated by ` + "`ginplate make:command`" + `.
// It is auto-registered above: rebuild and it appears as
// ` + "`ginplate {{.Use}}`" + ` with no further edits.
func {{.Constructor}}() *cobra.Command {
	return &cobra.Command{
		Use:   "{{.Use}}",
		Short: "TODO: describe {{.Use}}",
		RunE: func(cmd *cobra.Command, _ []string) error {
			// TODO: your logic here (call into pkg/app or internal/modules).
			// Fails until implemented so automation never mistakes a stub
			// for a working command.
			return fmt.Errorf("command %q is not implemented", "{{.Use}}")
		},
	}
}
`))

// generatedTemplate renders pkg/commands/generated.go (rewritten from disk
// on every run — never hand-edit it).
var generatedTemplate = template.Must(template.New("generated").Parse(`package commands

// Code generated by ` + "`ginplate make:command`" + `. DO NOT EDIT BY HAND.
// Regenerate with: ginplate make:command --sync
{{if .Imports}}import (
{{- range .Imports}}
	_ "{{.}}"
{{- end}}
)
{{end}}`))

type generatedData struct {
	Imports []string
}

func renderCommand(n commandNames) ([]byte, error) {
	var sb strings.Builder
	if err := commandTemplate.Execute(&sb, n); err != nil {
		return nil, err
	}
	return format.Source([]byte(sb.String()))
}

// modulePath reads the module path from go.mod (run from repo root).
func modulePath() (string, error) {
	data, err := os.ReadFile("go.mod")
	if err != nil {
		return "", fmt.Errorf("read go.mod (run from repo root): %w", err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		if mod, ok := strings.CutPrefix(strings.TrimSpace(line), "module "); ok {
			if mod = strings.TrimSpace(mod); mod != "" {
				return mod, nil
			}
		}
	}
	return "", fmt.Errorf("no module line in go.mod")
}

// moduleRelDir resolves dir to a module-relative slash path.
func moduleRelDir(dir string) (string, error) {
	if filepath.IsAbs(dir) {
		return "", fmt.Errorf("use a module-relative --dir (got absolute %q)", dir)
	}
	rel := filepath.Clean(dir)
	if rel == "." || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("use a module-relative --dir inside the repo (got %q)", dir)
	}
	return filepath.ToSlash(rel), nil
}

// generateCommand validates the name, renders the stub, writes it, and
// refreshes the generated import list.
func generateCommand(cmd *cobra.Command, pkgdir, dir, raw string, force, dryRun bool) error {
	n, err := deriveNames(raw)
	if err != nil {
		return err
	}
	module, err := modulePath()
	if err != nil {
		return err
	}
	n.Module = module
	src, err := renderCommand(n)
	if err != nil {
		return err
	}
	subdir := filepath.Join(dir, n.Dir)
	path := filepath.Join(subdir, n.File)
	if dryRun {
		cmd.Println(string(src))
		return nil
	}
	if _, err := os.Stat(path); err == nil && !force {
		return fmt.Errorf("file %s already exists (use --force to overwrite)", path)
	}
	if err := os.MkdirAll(subdir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, src, 0o644); err != nil {
		return err
	}
	cmd.Printf("created %s\n", path)
	return syncCustomImports(cmd, pkgdir, dir, dryRun)
}

// syncCustomImports regenerates pkg/commands/generated.go from disk.
func syncCustomImports(cmd *cobra.Command, pkgdir, dir string, dryRun bool) error {
	module, err := modulePath()
	if err != nil {
		return err
	}
	relDir, err := moduleRelDir(dir)
	if err != nil {
		return err
	}
	if _, err := moduleRelDir(pkgdir); err != nil {
		return err
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			entries = nil
		} else {
			return err
		}
	}
	var imports []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		sub := filepath.Join(dir, e.Name())
		files, err := os.ReadDir(sub)
		if err != nil {
			return err
		}
		hasGo := false
		for _, f := range files {
			if !f.IsDir() && strings.HasSuffix(f.Name(), ".go") {
				hasGo = true
				break
			}
		}
		if hasGo {
			imports = append(imports, module+"/"+relDir+"/"+e.Name())
		}
	}
	var sb strings.Builder
	if err := generatedTemplate.Execute(&sb, generatedData{Imports: imports}); err != nil {
		return err
	}
	src, err := format.Source([]byte(sb.String()))
	if err != nil {
		return err
	}
	path := filepath.Join(pkgdir, "generated.go")
	if dryRun {
		cmd.Printf("--- %s ---\n%s\n", path, src)
		return nil
	}
	if err := os.MkdirAll(pkgdir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, src, 0o644); err != nil {
		return err
	}
	cmd.Printf("synced %s (%d command packages)\n", path, len(imports))
	return nil
}
