package makeexception

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

// NewMakeExceptionCmd builds the `make:exception` generator: scaffolds a
// domain error type plus a self-registering mapper (--status sets the code).
func NewMakeExceptionCmd() *cobra.Command {
	var dir string
	var statusCode int
	var forceOverwrite, dryRunPrint bool
	cmd := &cobra.Command{
		Use:   "make:exception <Name>",
		Short: "Generate a new domain error type + mapper in internal/exceptions",
		Long: `Generate a domain error stub in internal/exceptions, e.g.:

	ginplate make:exception PaymentRequired --status 402   # internal/exceptions/payment_required.go

The stub declares a *PaymentRequiredError type and registers a mapper via
init() through web.RegisterErrorMapper, so services returning it (even
wrapped) render the mapped status after rebuilding with no further edits.
Status must be 400-599 (default 422).`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return generateException(cmd, dir, args[0], statusCode, forceOverwrite, dryRunPrint)
		},
	}
	cmd.Flags().StringVar(&dir, "dir", "internal/exceptions", "Directory for generated exception files (module-relative, run from repo root)")
	cmd.Flags().IntVar(&statusCode, "status", 422, "HTTP status the error maps to (400-599)")
	cmd.Flags().BoolVar(&forceOverwrite, "force", false, "Overwrite the file if it already exists")
	cmd.Flags().BoolVar(&dryRunPrint, "dry-run", false, "Print the file instead of writing it")
	return cmd
}

type exceptionNames struct {
	Raw    string // e.g. PaymentRequired (as typed, for the generated comment)
	Use    string // e.g. payment-required (mapper registry name)
	File   string // e.g. payment_required.go
	Type   string // e.g. PaymentRequiredError (concrete error type)
	Status int    // e.g. 402
	Module string // e.g. github.com/idehen-divine/GinPlate (from go.mod)
}

var validExceptionNameRe = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_-]*$`)

// deriveExceptionNames maps a name in any style to file, type, and registry names.
func deriveExceptionNames(raw string) (exceptionNames, error) {
	raw = strings.TrimSpace(raw)
	if !validExceptionNameRe.MatchString(raw) {
		return exceptionNames{}, fmt.Errorf("invalid name %q: use letters, digits, '-' or '_' (start with a letter)", raw)
	}
	var words []string
	for _, part := range strings.FieldsFunc(raw, func(r rune) bool { return r == '-' || r == '_' || r == ' ' }) {
		words = append(words, splitCamel(part)...)
	}
	lower := make([]string, len(words))
	studly := ""
	for i, w := range words {
		lower[i] = strings.ToLower(w)
		studly += capitalize(w)
	}
	return exceptionNames{
		Raw:  strings.TrimSpace(raw),
		Use:  strings.Join(lower, "-"),
		File: strings.Join(lower, "_") + ".go",
		Type: studly + "Error",
	}, nil
}

func splitCamel(s string) []string {
	var words []string
	start := 0
	for i := 1; i < len(s); i++ {
		c, p := s[i], s[i-1]
		if c >= 'A' && c <= 'Z' && ((p >= 'a' && p <= 'z') || (p >= '0' && p <= '9')) {
			words = append(words, s[start:i])
			start = i
		}
	}
	return append(words, s[start:])
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + strings.ToLower(s[1:])
}

var exceptionTemplate = template.Must(template.New("exception").Parse(`package exceptions

import (
	"errors"

	"{{.Module}}/pkg/web"
)

// {{.Type}} was generated by ` + "`ginplate make:exception {{.Raw}} --status {{.Status}}`" + `.
// Return it (even wrapped with %w) from services; web.Render maps it to
// {{.Status}} after rebuilding with no further edits. Message is
// client-safe; Cause stays server-side unless APP_DEBUG is true.
type {{.Type}} struct {
	Message string
	Cause   error
}

func (e *{{.Type}}) Error() string {
	if e.Cause != nil {
		return e.Message + ": " + e.Cause.Error()
	}
	return e.Message
}

func (e *{{.Type}}) Unwrap() error { return e.Cause }

func init() {
	web.RegisterErrorMapper("{{.Use}}", func(err error) (*web.AppError, bool) {
		var target *{{.Type}}
		if !errors.As(err, &target) {
			return nil, false
		}
		msg := target.Message
		if msg == "" {
			msg = "{{.Use}}"
		}
		ae := web.New({{.Status}}, msg)
		ae.Err = target.Cause
		return ae, true
	})
}
`))

func renderException(n exceptionNames) ([]byte, error) {
	var sb strings.Builder
	if err := exceptionTemplate.Execute(&sb, n); err != nil {
		return nil, err
	}
	return format.Source([]byte(sb.String()))
}

// modulePath reads the module path from go.mod (run from repo root).
func modulePath() (string, error) {
	data, err := os.ReadFile("go.mod")
	if err != nil {
		return "", fmt.Errorf("read go.mod (run from repo root): %w", err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		if mod, ok := strings.CutPrefix(strings.TrimSpace(line), "module "); ok {
			if mod = strings.TrimSpace(mod); mod != "" {
				return mod, nil
			}
		}
	}
	return "", fmt.Errorf("no module line in go.mod")
}

// generateException validates the name and status, renders the stub, and
// writes it into --dir (same package, so no import sync is needed).
func generateException(cmd *cobra.Command, dir, raw string, status int, force, dryRun bool) error {
	n, err := deriveExceptionNames(raw)
	if err != nil {
		return err
	}
	if status < 400 || status > 599 {
		return fmt.Errorf("invalid status %d: must be 400-599", status)
	}
	n.Status = status
	module, err := modulePath()
	if err != nil {
		return err
	}
	n.Module = module
	src, err := renderException(n)
	if err != nil {
		return err
	}
	path := filepath.Join(dir, n.File)
	if dryRun {
		cmd.Println(string(src))
		return nil
	}
	if _, err := os.Stat(path); err == nil && !force {
		return fmt.Errorf("file %s already exists (use --force to overwrite)", path)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, src, 0o644); err != nil {
		return err
	}
	cmd.Printf("created %s\n", path)
	return nil
}
