package makenotification

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

// NewMakeNotificationCmd builds the `make:notification` generator:
// `ginplate make:notification OrderShipped` writes
// internal/notifications/order_shipped/order_shipped.go — its own directory
// and Go package — containing a Notification stub fanning out to the
// database and mail channels. Handlers then deliver it in one line:
//
//	notify.Send(ctx, notifier, to, ordershipped.OrderShipped{...})
func NewMakeNotificationCmd() *cobra.Command {
	var dir string
	var force, dryRun bool
	cmd := &cobra.Command{
		Use:   "make:notification <Name>",
		Short: "Generate a new notification (database + mail channels)",
		Long: `Generate a notification stub in its own directory, e.g.:

	ginplate make:notification OrderShipped   # writes internal/notifications/order_shipped/order_shipped.go

Fill in Via/ToMail/ToDatabase, then deliver it inline or queued with no
further wiring. For rich templated mail, run ` + "`ginplate make:mail`" + ` and
return that mailable from ToMail.`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return generateNotification(cmd, dir, args[0], force, dryRun)
		},
	}
	cmd.Flags().StringVar(&dir, "dir", "internal/notifications", "Parent directory for generated notification folders (module-relative, run from repo root)")
	cmd.Flags().BoolVar(&force, "force", false, "Overwrite the file if it already exists")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Print the file instead of writing it")
	return cmd
}

// notificationNames holds the derived identifiers for a notification.
type notificationNames struct {
	Struct string // e.g. OrderShipped (notification struct)
	Dir    string // e.g. order_shipped (subdirectory under --dir)
	Pkg    string // e.g. ordershipped (Go package name: letters+digits only)
	File   string // e.g. order_shipped.go
	Type   string // e.g. order-shipped (stored discriminator)
	Module string // e.g. github.com/idehen-divine/GinPlate (from go.mod)
}

var validNameRe = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_-]*$`)

// deriveNames maps a user-supplied name (OrderShipped, order-shipped,
// order_shipped) to struct, file, package, and type identifiers.
func deriveNames(raw string) (notificationNames, error) {
	raw = strings.TrimSpace(raw)
	if !validNameRe.MatchString(raw) {
		return notificationNames{}, fmt.Errorf("invalid name %q: use letters, digits, '-' or '_' (start with a letter)", raw)
	}
	var words []string
	for _, part := range strings.FieldsFunc(raw, func(r rune) bool { return r == '-' || r == '_' || r == ' ' }) {
		words = append(words, splitCamel(part)...)
	}
	lower := make([]string, len(words))
	for i, w := range words {
		lower[i] = strings.ToLower(w)
	}
	studly := ""
	for _, w := range words {
		studly += capitalize(w)
	}
	return notificationNames{
		Struct: studly,
		Dir:    strings.Join(lower, "_"),
		Pkg:    strings.Join(lower, ""),
		File:   strings.Join(lower, "_") + ".go",
		Type:   strings.Join(lower, "-"),
	}, nil
}

// splitCamel splits "OrderShipped" into ["Order" "Shipped"].
func splitCamel(s string) []string {
	var words []string
	start := 0
	for i := 1; i < len(s); i++ {
		c, p := s[i], s[i-1]
		if c >= 'A' && c <= 'Z' && ((p >= 'a' && p <= 'z') || (p >= '0' && p <= '9')) {
			words = append(words, s[start:i])
			start = i
		}
	}
	return append(words, s[start:])
}

// capitalize uppercases the first letter and lowercases the rest, turning a
// word into its StudlyCase segment.
func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + strings.ToLower(s[1:])
}

var notificationTemplate = template.Must(template.New("notification").Parse(`// Package {{.Pkg}} is the {{.Dir}} notification: one event fanning out
// to the database inbox and the mailbox.
package {{.Pkg}}

import (
	"{{.Module}}/pkg/mail"
	"{{.Module}}/pkg/notify"
)

// {{.Struct}} was generated by ` + "`ginplate make:notification`" + `.
// Fill in the fields your channels need, then deliver it:
//
//	notify.Send(ctx, notifier, to, {{.Struct}}{...})      // inline, now
//	notify.Queue(ctx, notifier, q, to, {{.Struct}}{...})  // background job
type {{.Struct}} struct {
	Name  string
	Email string
}

// Type is the stored discriminator.
func (m {{.Struct}}) Type() string { return "{{.Type}}" }

// Via names the channels. Drop one to skip it; add future channels
// (sms, slack, ...) after registering them on the notifier.
func (m {{.Struct}}) Via() []string { return []string{notify.ChannelDatabase, notify.ChannelMail} }

// ToMail is the mail payload. For rich templated mail, run
// ` + "`ginplate make:mail`" + ` and return that mailable's Build() here.
func (m {{.Struct}}) ToMail() (mail.Message, error) {
	return mail.Message{
		To:      []string{m.Email},
		Subject: "TODO: subject",
		Text:    "TODO: body for " + m.Name,
	}, nil
}

// ToDatabase is the inbox payload, rendered in the notifications list.
func (m {{.Struct}}) ToDatabase() (map[string]any, error) {
	return map[string]any{
		"title": "TODO: title",
		"body":  "TODO: body for " + m.Name,
	}, nil
}

var _ notify.Notification = {{.Struct}}{}
`))

// renderNotification renders the stub source, gofmt-formatted.
func renderNotification(n notificationNames) ([]byte, error) {
	var sb strings.Builder
	if err := notificationTemplate.Execute(&sb, n); err != nil {
		return nil, err
	}
	return format.Source([]byte(sb.String()))
}

// modulePath reads the module path from go.mod in the working directory,
// so generated import paths survive a cloner renaming the module.
func modulePath() (string, error) {
	data, err := os.ReadFile("go.mod")
	if err != nil {
		return "", fmt.Errorf("read go.mod (run from repo root): %w", err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		if mod, ok := strings.CutPrefix(strings.TrimSpace(line), "module "); ok {
			if mod = strings.TrimSpace(mod); mod != "" {
				return mod, nil
			}
		}
	}
	return "", fmt.Errorf("no module line in go.mod")
}

// generateNotification validates the name, renders the stub, and writes it
// into its own directory. Dry-run prints instead of writing.
func generateNotification(cmd *cobra.Command, dir, raw string, force, dryRun bool) error {
	n, err := deriveNames(raw)
	if err != nil {
		return err
	}
	// Module path keeps generated imports correct after a cloner renames
	// the module.
	module, err := modulePath()
	if err != nil {
		return err
	}
	n.Module = module
	src, err := renderNotification(n)
	if err != nil {
		return err
	}
	subdir := filepath.Join(dir, n.Dir)
	path := filepath.Join(subdir, n.File)
	if dryRun {
		cmd.Printf("--- %s ---\n%s\n", path, src)
		return nil
	}
	if _, err := os.Stat(path); err == nil && !force {
		return fmt.Errorf("file %s already exists (use --force to overwrite)", path)
	}
	if err := os.MkdirAll(subdir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, src, 0o644); err != nil {
		return err
	}
	cmd.Printf("created %s\n", path)
	return nil
}
