package makemiddleware

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

// NewMakeMiddlewareCmd builds the `make:middleware` generator: scaffolds a
// shared per-route guard stub, or a self-registering global with --global.
func NewMakeMiddlewareCmd() *cobra.Command {
	var dir string
	var global, force, dryRun bool
	cmd := &cobra.Command{
		Use:   "make:middleware <Name>",
		Short: "Generate a new middleware stub in internal/middleware",
		Long: `Generate a middleware stub in internal/middleware, e.g.:

	ginplate make:middleware AuditLog            # internal/middleware/audit_log.go, shared per-route guard (no init)
	ginplate make:middleware RequestID --global  # internal/middleware/request_id.go, global (self-registers via init())

Per-route guards export a gin.HandlerFunc constructor for use in a
module's routes.go g.Use(...) line, plus one web.RegisterRouteMeta line so
` + "`route:list`" + ` shows it. Global guards register themselves via init()
through web.RegisterGlobalMiddleware, so they run on every request after
rebuilding with no further edits.`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return generateMiddleware(cmd, dir, args[0], global, force, dryRun)
		},
	}
	cmd.Flags().StringVar(&dir, "dir", "internal/middleware", "Directory for generated middleware files (module-relative, run from repo root)")
	cmd.Flags().BoolVar(&global, "global", false, "Generate a global middleware (self-registers via init) instead of a shared per-route guard")
	cmd.Flags().BoolVar(&force, "force", false, "Overwrite the file if it already exists")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Print the file instead of writing it")
	return cmd
}

type middlewareNames struct {
	Raw    string // e.g. AuditLog (as typed, for the generated comment)
	Use    string // e.g. audit-log (registry name for --global)
	File   string // e.g. audit_log.go
	Func   string // e.g. AuditLog (constructor)
	Label  string // e.g. audit-log (suggested route:list label suffix)
	Module string // e.g. github.com/idehen-divine/GinPlate (from go.mod)
	Global bool
}

var validMiddlewareNameRe = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_-]*$`)

// deriveMiddlewareNames maps a name in any style to file, func, registry,
// and label identifiers.
func deriveMiddlewareNames(raw string) (middlewareNames, error) {
	raw = strings.TrimSpace(raw)
	if !validMiddlewareNameRe.MatchString(raw) {
		return middlewareNames{}, fmt.Errorf("invalid name %q: use letters, digits, '-' or '_' (start with a letter)", raw)
	}
	var words []string
	for _, part := range strings.FieldsFunc(raw, func(r rune) bool { return r == '-' || r == '_' || r == ' ' }) {
		words = append(words, splitCamel(part)...)
	}
	lower := make([]string, len(words))
	studly := ""
	for i, w := range words {
		lower[i] = strings.ToLower(w)
		studly += capitalize(w)
	}
	return middlewareNames{
		Raw:   strings.TrimSpace(raw),
		Use:   strings.Join(lower, "-"),
		File:  strings.Join(lower, "_") + ".go",
		Func:  studly,
		Label: strings.Join(lower, "-"),
	}, nil
}

func splitCamel(s string) []string {
	var words []string
	start := 0
	for i := 1; i < len(s); i++ {
		c, p := s[i], s[i-1]
		if c >= 'A' && c <= 'Z' && ((p >= 'a' && p <= 'z') || (p >= '0' && p <= '9')) {
			words = append(words, s[start:i])
			start = i
		}
	}
	return append(words, s[start:])
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + strings.ToLower(s[1:])
}

var globalMiddlewareTemplate = template.Must(template.New("global").Parse(`package middleware

import (
	"github.com/gin-gonic/gin"

	"{{.Module}}/pkg/web"
)

func init() {
	web.RegisterGlobalMiddleware("{{.Use}}", web.DefaultGlobalMiddlewareOrder, func(router *gin.Engine, _ *web.ModuleDeps) {
		router.Use({{.Func}}())
	})
}

// {{.Func}} was generated by ` + "`ginplate make:middleware {{.Raw}} --global`" + `.
// It is auto-registered above: rebuild and it runs on every request after
// all built-ins (logger … ProvideDB) with no further edits. It must only
// capture deps at registration and touch them when serving, so ` + "`route:list`" + `
// (nil backends) stays safe.
func {{.Func}}() gin.HandlerFunc {
	return func(c *gin.Context) {
		// TODO: your logic here. c.Next() to continue, or
		// web.Fail + c.Abort() to stop.
		c.Next()
	}
}
`))

var routeMiddlewareTemplate = template.Must(template.New("route").Parse(`package middleware

import (
	"github.com/gin-gonic/gin"
)

// {{.Func}} was generated by ` + "`ginplate make:middleware {{.Raw}}`" + `.
// It is a shared per-route guard (no init): use it in any module's routes.go,
// e.g. g.Use(middleware.RequireAuth(key, store), middleware.{{.Func}}()), plus one
// web.RegisterRouteMeta line in the same init() so ` + "`route:list`" + ` shows it,
// e.g. web.RegisterRouteMeta("GET", "/api/v1/<path>", "auth+{{.Label}}").
//
// It must not touch deps at construction (nil-safe for ` + "`route:list`" + `);
// only touch them inside the returned func when serving. Shape it like
// middleware.RequireRole: check → c.Next(), or web.Fail + c.Abort() to stop.
func {{.Func}}() gin.HandlerFunc {
	return func(c *gin.Context) {
		// TODO: your logic here.
		c.Next()
	}
}
`))

func renderMiddleware(n middlewareNames) ([]byte, error) {
	var sb strings.Builder
	tmpl := routeMiddlewareTemplate
	if n.Global {
		tmpl = globalMiddlewareTemplate
	}
	if err := tmpl.Execute(&sb, n); err != nil {
		return nil, err
	}
	return format.Source([]byte(sb.String()))
}

// modulePath reads the module path from go.mod (run from repo root).
func modulePath() (string, error) {
	data, err := os.ReadFile("go.mod")
	if err != nil {
		return "", fmt.Errorf("read go.mod (run from repo root): %w", err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		if mod, ok := strings.CutPrefix(strings.TrimSpace(line), "module "); ok {
			if mod = strings.TrimSpace(mod); mod != "" {
				return mod, nil
			}
		}
	}
	return "", fmt.Errorf("no module line in go.mod")
}

// generateMiddleware validates the name, renders the stub, and writes it
// into --dir (same package, so no import sync is needed).
func generateMiddleware(cmd *cobra.Command, dir, raw string, global, force, dryRun bool) error {
	n, err := deriveMiddlewareNames(raw)
	if err != nil {
		return err
	}
	n.Global = global
	module, err := modulePath()
	if err != nil {
		return err
	}
	n.Module = module
	src, err := renderMiddleware(n)
	if err != nil {
		return err
	}
	path := filepath.Join(dir, n.File)
	if dryRun {
		cmd.Println(string(src))
		return nil
	}
	if _, err := os.Stat(path); err == nil && !force {
		return fmt.Errorf("file %s already exists (use --force to overwrite)", path)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, src, 0o644); err != nil {
		return err
	}
	cmd.Printf("created %s\n", path)
	return nil
}
