package key

import (
	"crypto/rand"
	"encoding/base64"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

// NewKeyGenerateCmd builds `ginplate key:generate`: creates a random 32-byte
// APP_KEY and writes it into the env file. Run once per environment.
func NewKeyGenerateCmd() *cobra.Command {
	var envFile string
	var show bool
	cmd := &cobra.Command{
		Use:   "key:generate",
		Short: "Generate APP_KEY and write it into the env file",
		RunE: func(cmd *cobra.Command, _ []string) error {
			raw := make([]byte, 32)
			if _, err := rand.Read(raw); err != nil {
				return err
			}
			key := "base64:" + base64.StdEncoding.EncodeToString(raw)
			if show {
				cmd.Println(key)
				return nil
			}
			if err := writeKey(envFile, key); err != nil {
				return err
			}
			cmd.Printf("APP_KEY written to %s (restart to pick it up)\n", envFile)
			return nil
		},
	}
	cmd.Flags().StringVar(&envFile, "env-file", ".env", "Env file to update")
	cmd.Flags().BoolVar(&show, "show", false, "Print the key instead of writing it")
	return cmd
}

// writeFileSecure writes data with owner-only permissions (enforced via
// Chmod, since WriteFile's mode applies only to new files).
func writeFileSecure(path string, data []byte) error {
	if err := os.WriteFile(path, data, 0o600); err != nil {
		return err
	}
	return os.Chmod(path, 0o600)
}

// writeKey replaces the APP_KEY line in path, appending when missing.
func writeKey(path, key string) error {
	data, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	if os.IsNotExist(err) {
		return writeFileSecure(path, []byte("# Generated by `ginplate key:generate`.\nAPP_KEY="+key+"\n"))
	}
	var out []string
	found := false
	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") || !strings.HasPrefix(trimmed, "APP_KEY=") {
			out = append(out, line)
			continue
		}
		out = append(out, "APP_KEY="+key)
		found = true
	}
	if !found {
		for len(out) > 0 && strings.TrimSpace(out[len(out)-1]) == "" {
			out = out[:len(out)-1]
		}
		out = append(out, "APP_KEY="+key, "")
	}
	return writeFileSecure(path, []byte(strings.Join(out, "\n")))
}
