package makemail

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

// NewMakeMailCmd builds the `make:mail` generator: scaffolds a mailable
// struct beside its HTML template.
func NewMakeMailCmd() *cobra.Command {
	var dir string
	var force, dryRun bool
	cmd := &cobra.Command{
		Use:   "make:mail <Name>",
		Short: "Generate a new mailable (struct + template side by side)",
		Long: `Generate a mailable in its own directory, e.g.:

	ginplate make:mail OrderShipped   # writes internal/mail/order_shipped/order_shipped.go + .html

Edit the struct fields and the template, then send it from any handler via
appmail.Send / appmail.Queue with no further wiring.`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return generateMail(cmd, dir, args[0], force, dryRun)
		},
	}
	cmd.Flags().StringVar(&dir, "dir", "internal/mail", "Parent directory for generated mail folders (module-relative, run from repo root)")
	cmd.Flags().BoolVar(&force, "force", false, "Overwrite the files if they already exist")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Print the files instead of writing them")
	return cmd
}

type mailNames struct {
	Struct   string // e.g. OrderShipped (mailable struct)
	Dir      string // e.g. order_shipped (subdirectory under --dir)
	Pkg      string // e.g. ordershipped (Go package name: letters+digits only)
	File     string // e.g. order_shipped.go
	Template string // e.g. order_shipped.html
	Module   string // e.g. github.com/idehen-divine/GinPlate (from go.mod)
}

var validNameRe = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_-]*$`)

// deriveNames maps a name in any style to struct, file, and template identifiers.
func deriveNames(raw string) (mailNames, error) {
	raw = strings.TrimSpace(raw)
	if !validNameRe.MatchString(raw) {
		return mailNames{}, fmt.Errorf("invalid name %q: use letters, digits, '-' or '_' (start with a letter)", raw)
	}
	var words []string
	for _, part := range strings.FieldsFunc(raw, func(r rune) bool { return r == '-' || r == '_' || r == ' ' }) {
		words = append(words, splitCamel(part)...)
	}
	lower := make([]string, len(words))
	for i, w := range words {
		lower[i] = strings.ToLower(w)
	}
	studly := ""
	for _, w := range words {
		studly += capitalize(w)
	}
	snake := strings.Join(lower, "_")
	return mailNames{
		Struct:   studly,
		Dir:      snake,
		Pkg:      strings.Join(lower, ""),
		File:     snake + ".go",
		Template: snake + ".html",
	}, nil
}

func splitCamel(s string) []string {
	var words []string
	start := 0
	for i := 1; i < len(s); i++ {
		c, p := s[i], s[i-1]
		if c >= 'A' && c <= 'Z' && ((p >= 'a' && p <= 'z') || (p >= '0' && p <= '9')) {
			words = append(words, s[start:i])
			start = i
		}
	}
	return append(words, s[start:])
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + strings.ToLower(s[1:])
}

var mailableTemplate = template.Must(template.New("mailable").Parse(`// Package {{.Pkg}} is the {{.Dir}} mailable: its struct beside its
// template, so the whole email lives in this directory.
package {{.Pkg}}

import (
	"embed"

	pkgmail "{{.Module}}/pkg/mail"
)

//go:embed *.html
var templateFS embed.FS

// {{.Struct}} was generated by ` + "`ginplate make:mail`" + `. Fill in the
// fields your template needs, then send it from any handler:
//
//	appmail.Send(ctx, sender, m.Email, {{.Struct}}{...})
//
// To preview it via POST /api/v1/mail/preview/{{.Dir}} (debug only), add one
// entry to the mailables map in internal/mail/mail.go.
type {{.Struct}} struct {
	Name  string
	Email string
}

// Build renders {{.Template}} into a ready-to-send Message.
func (m {{.Struct}}) Build() (pkgmail.Message, error) {
	html, err := pkgmail.RenderFS(templateFS, "{{.Dir}}", m)
	if err != nil {
		return pkgmail.Message{}, err
	}
	return pkgmail.Message{
		To:      []string{m.Email},
		Subject: "TODO: subject",
		HTML:    html,
		Text:    pkgmail.StripTags(html),
		Tags:    map[string]string{"kind": "{{.Dir}}"},
	}, nil
}

var _ pkgmail.Mailable = {{.Struct}}{}
`))

var htmlTemplate = template.Must(template.New("html").Parse(`<!doctype html>
<html>
  <body style="font-family: sans-serif; color: #111;">
    <h1>Hi {{"{{.Name}}"}}!</h1>
    <p>TODO: your {{.Dir}} email body.</p>
  </body>
</html>
`))

func renderMailable(n mailNames) ([]byte, error) {
	var sb strings.Builder
	if err := mailableTemplate.Execute(&sb, n); err != nil {
		return nil, err
	}
	return format.Source([]byte(sb.String()))
}

func renderHTML(n mailNames) ([]byte, error) {
	var sb strings.Builder
	if err := htmlTemplate.Execute(&sb, n); err != nil {
		return nil, err
	}
	return []byte(sb.String()), nil
}

// modulePath reads the module path from go.mod (run from repo root).
func modulePath() (string, error) {
	data, err := os.ReadFile("go.mod")
	if err != nil {
		return "", fmt.Errorf("read go.mod (run from repo root): %w", err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		if mod, ok := strings.CutPrefix(strings.TrimSpace(line), "module "); ok {
			if mod = strings.TrimSpace(mod); mod != "" {
				return mod, nil
			}
		}
	}
	return "", fmt.Errorf("no module line in go.mod")
}

// generateMail validates the name and writes the stub pair into its directory.
func generateMail(cmd *cobra.Command, dir, raw string, force, dryRun bool) error {
	n, err := deriveNames(raw)
	if err != nil {
		return err
	}
	module, err := modulePath()
	if err != nil {
		return err
	}
	n.Module = module
	src, err := renderMailable(n)
	if err != nil {
		return err
	}
	html, err := renderHTML(n)
	if err != nil {
		return err
	}
	subdir := filepath.Join(dir, n.Dir)
	goPath := filepath.Join(subdir, n.File)
	htmlPath := filepath.Join(subdir, n.Template)
	if dryRun {
		cmd.Printf("--- %s ---\n%s\n--- %s ---\n%s\n", goPath, src, htmlPath, html)
		return nil
	}
	if _, err := os.Stat(goPath); err == nil && !force {
		return fmt.Errorf("file %s already exists (use --force to overwrite)", goPath)
	}
	if _, err := os.Stat(htmlPath); err == nil && !force {
		return fmt.Errorf("file %s already exists (use --force to overwrite)", htmlPath)
	}
	if err := os.MkdirAll(subdir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(goPath, src, 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(htmlPath, html, 0o644); err != nil {
		return err
	}
	cmd.Printf("created %s\ncreated %s\n", goPath, htmlPath)
	return nil
}
